export const HAMBURGER_MENU = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAb1BMVEX///8iICGSkZIkHyEPDA3z8vIyMTEhGx40MDEeHB4jICEeHR4AAAAxMTEgHh4gHB3W1tYtKyyXlpe6uroKBQhzcnJ+fX7CwsKysrJmZWX19fXk5OQYFhc5ODgoJidta2xUVFRfXV7Kysqsq6yjo6MHDa+eAAAB8UlEQVR4nO3c3VLaQBgGYJY/IQtE1Iogrfbn/q+xCaQ2TqtFm222+jwHDC8MMO8EdjnY+QYDAAAAAAAAAAAAAAAAeI/OL4Z5uDhP0m+yXYwzcbX4cJug4d045GN8Pem84GYd+67VUq6/dN7wou9Sjy1u0jQcjUZ9V2skaHhZfUuLbBrGYtN5w8F2HLNpGFOsNIPddlo3XGUgTK9T7BbVFzWbHX+zS1IQAAAAAAAAAABeZJKHVPXO76dHs9msul1OH+JfpOmr0ufuz15Wbhb78uzBvJzPWym2U/XU6Sk+lc6eTnEfv3Zf8PZjeTib2AihnYpwOJl5Qhp1kULY33d/1Pvbp9XTDcO/bhjGl503HD5uUX/Mn1PxTPr964pTUkhygra+hj9U16V10LS6+/pUtFLxTAo/00GCa1j/DhtFDw2Lxw1T/A7rtTRWS+ZhES2rdS3O22lep/qBX1LZSmetFI+pfvzk1HximrW03g9ns4edadboIy2XafbDWt9/Zhqp6gEAAAAAAAAAwAu89Zl7u+00xFXse2ZiLdHcxO24PLx7DpLMvrxcHy9f3+WOUswvHYZVRg2TTNktqnqjTCa0Jmm4WZcZNUwxC3pwd5VPwyLJlN3JdnHV9zD2RqKZ7G9/rj4AAAAAAAAAAAAAAAD8T74DVhZG6MsBqOQAAAAASUVORK5CYII='

export const YOUTUBE_LOGO = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Logo_of_YouTube_%282015-2017%29.svg/1280px-Logo_of_YouTube_%282015-2017%29.svg.png'

export const USER_ICON = 'https://cdn-icons-png.flaticon.com/512/666/666201.png'

const YOUTUBE_API_KEY = 'AIzaSyBgOy-xb0OWkTprR_gqR-OYTtRUp7nPbGA'

export const YOUTUBE_VIDEOS_API = `https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&maxResults=50&regionCode=IN&key=${YOUTUBE_API_KEY}`

export const YOUTUBE_SEARCH_RECOMMENDATION_API = 'https://suggestqueries.google.com/complete/search?client=firefox&ds=yt&q='

export const YOUTUBE_SEARCH_API = `https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&key=${YOUTUBE_API_KEY}&q=`

export const OFFSET_LIVE_CHAT = 20;

const names = [
    'Amit Kumar',
    'Priya Singh',
    'Rajesh Patel',
    'Anita Sharma',
    'Rahul Verma',
    'Sneha Gupta',
    'Vikram Yadav',
    'Pooja Choudhary',
    'Sachin Mehta',
    'Neha Joshi',
    'Vishal Malhotra',
    'Divya Tiwari',
    'Arun Khanna',
    'Rashmi Singhania',
    'Anil Reddy',
    'Kavita Pandey',
    'Ravi Kapoor',
    'Shikha Saxena',
    'Nitin Sharma',
    'Sarika Varma',
    'Manoj Agarwal',
    'Geeta Patel',
    'Ramesh Kumar',
    'Meenakshi Rana',
    'Rajiv Singh',
    'Shweta Goyal',
    'Amitabh Srivastava',
    'Sunita Jain',
    'Prakash Mishra',
    'Kiran Chopra',
    'Sanjay Gupta',
    'Monika Sharma',
    'Rahul Mehra',
    'Anjali Verma',
    'Rajendra Yadav',
    'Nisha Kapoor',
    'Alok Saxena',
    'Anju Malhotra',
    'Vijay Choudhary',
    'Deepika Tiwari',
    'Gaurav Khanna',
    'Priyanka Singh',
    'Rakesh Reddy',
    'Preeti Pandey',
    'Arvind Kumar',
    'Swati Varma',
    'Dinesh Agarwal',
    'Ritu Patel',
    'Harish Mehta',
    'Anita Joshi',
    "Suresh Kumar",
  "Anjali Gupta",
  "Rajendra Singh",
  "Nisha Verma",
  "Amit Sharma",
  "Pooja Reddy",
  "Vikram Kapoor",
  "Rita Patel",
  "Arun Kumar",
  "Neeta Malhotra",
  "Vijay Bansal",
  "Deepika Chopra",
  "Harish Tiwari",
  "Seema Yadav",
  "Rajesh Rana",
  "Priyanka Joshi",
  "Sanjay Agarwal",
  "Monika Rawat",
  "Rahul Khanna",
  "Kavita Choudhary",
  "Sachin Mehta",
  "Anita Saxena",
  "Vishal Pandey",
  "Divya Shukla",
  "Alok Mishra",
  "Geeta Singhania",
  "Ramesh Varma",
  "Neha Kapoor",
  "Rahul Jain",
  "Shweta Garg",
  "Amitabh Srivastava",
  "Sunita Mathur",
  "Prakash Sharma",
  "Kiran Verma",
  "Ravi Malhotra",
  "Sarika Bhatia",
  "Manoj Sood",
  "Anju Narang",
  "Rakesh Sethi",
  "Preeti Bajaj",
  "Arvind Chauhan",
  "Swati Kapoor",
  "Dinesh Mehta",
  "Ritu Rastogi",
  "Amit Verma",
  "Kusum Sharma",
  "Anil Tiwari",
  "Suman Saxena",
  "Vineet Aggarwal",
  "Meenakshi Malik",
  "Amit Jain",
  "Deepak Khurana",
  "Rina Kapoor",
  "Arun Verma",
  "Anuradha Chaturvedi",
  "Vikas Gupta",
  "Mamta Sharma",
  "Rohit Verma",
  "Rashmi Khanna",
  "Ajay Mathur",
  "Nidhi Kapoor",
  "Vikram Malhotra",
  "Rekha Joshi",
  "Sanjeev Rathi",
  "Ruchi Sharma",
  "Rajeev Kapoor",
  "Shilpa Mehra",
  "Amit Srivastava",
  "Savita Tiwari",
  "Rohit Choudhary",
  "Anamika Bajpai",
  "Vivek Goyal",
  "Sapna Rastogi",
  "Sunil Varma",
  "Pallavi Chauhan",
  "Sumit Sharma",
  "Neelam Kumar",
  "Rohini Yadav",
  "Aruna Mehra",
  "Rajnish Kapoor",
  "Neha Seth",
  "Anand Gupta",
  "Sangeeta Pandey",
  "Rahul Sharma",
  "Nisha Malhotra",
  "Vinod Tiwari",
  "Anjana Rani",
  "Deepak Gupta",
  "Poonam Joshi",
  "Rajat Verma",
  "Sonam Choudhary",
  "Sanjeev Mehra",
  "Shilpi Bansal",
  "Rakesh Varma",
  "Swati Mathur",
  "Amit Chauhan",
  "Ritu Kumar",
  "Anil Mehta",
  "Sarika Sharma",
  "Vivek Rastogi",
  "Savita Kapoor",
  ];


  const comments = [
    "Great video! Thanks for sharing.",
    "I learned a lot from this tutorial.",
    "This is so helpful!",
    "You explained it very well.",
    "Awesome content, keep it up!",
    "I've been looking for this information.",
    "This video changed my life!",
    "You're doing an amazing job!",
    "Can you make more videos like this?",
    "This deserves more views!",
    "I subscribed to your channel!",
    "Your content is top-notch.",
    "I wish I had found this earlier.",
    "You're a great teacher!",
    "Thanks for the valuable tips.",
    "This helped me with my project.",
    "I'm sharing this with my friends.",
    "You're the best!",
    "I love your channel!",
    "Please make more videos soon.",
    "You're so underrated.",
    "This is a game-changer!",
    "I can't thank you enough.",
    "Your explanation is crystal clear.",
    "This saved me so much time.",
    "I can't stop watching your videos.",
    "You make learning fun!",
    "This is exactly what I needed.",
    "I appreciate your hard work.",
    "You're my favorite YouTuber!",
    "This tutorial is a gem.",
    "You deserve more subscribers.",
    "I've been binge-watching your channel.",
    "You make it look so easy!",
    "This is gold!",
    "I'm a fan of your content.",
    "Your videos are life-savers.",
    "You have a talent for teaching.",
    "I'm grateful for your videos.",
    "This is pure genius!",
    "You're a YouTube legend!",
    "You're my go-to source now.",
    "I can't get enough of your videos.",
    "This is the best channel ever!",
    "Your work is impressive.",
    "I'm learning so much from you.",
    "You're a true expert.",
    "This is my favorite video so far.",
    "I'm inspired by your channel.",
    "You make complicated things easy.",
    "This is the best tutorial I've seen.",
    "You're changing lives with your content.",
    "I look forward to your new videos.",
    "This is a masterpiece!",
    "Your channel deserves recognition.",
    "You're a YouTube sensation!",
    "I recommend your channel to everyone.",
    "This deserves a million likes!",
    "You're making a difference.",
    "I've become a better person because of you.",
    "This video is a blessing.",
    "You're a YouTube superstar!",
    "I can't express how much I appreciate your work.",
    "This is beyond amazing!",
    "You're a true talent.",
    "I wish I could give this a thousand thumbs up.",
    "This video is changing the game.",
    "You're the best teacher on YouTube!",
    "I can't believe I found your channel.",
    "This is the holy grail of tutorials.",
    "You're a legend in the making.",
    "I'm grateful for your dedication.",
    "This is a game-changer!",
    "You're making the world a better place.",
    "I can't get enough of your videos.",
    "This is the content I've been searching for.",
    "You're a true inspiration.",
    "I've learned more from you than school.",
    "This video is pure gold.",
    "You're a YouTube genius!",
    "I wish I had found your channel sooner.",
    "This is top-tier content.",
    "You're my YouTube hero!",
    "I'm in awe of your knowledge.",
    "This is worth every second.",
    "You're the reason I love YouTube.",
    "I can't wait for your next video.",
    "This is a masterpiece!",
    "You're a true YouTube legend.",
    "I've shared this with everyone I know.",
    "This deserves all the awards.",
    "You're a true gem on YouTube.",
    "I can't stop watching your videos.",
    "This is the best thing I've seen all year.",
    "You're a YouTube icon!",
    "I've subscribed and turned on notifications.",
    "This is a must-watch for everyone.",
    "You're a gift to the YouTube community.",
    "I'm forever grateful for your content.",
    "This video is life-changing!",
    "You're a legend in the making.",
    "I've learned so much from you.",
    "This is a masterpiece!",
    "You're a true YouTube sensation.",
    "I can't thank you enough.",
    "This is the best video on the internet.",
    "You're my YouTube role model!",
    "I can't get enough of your wisdom.",
    "This video is a game-changer.",
    "You're the best thing on YouTube.",
    "I've become a fan for life.",
    "This deserves a million views.",
    "You're a YouTube legend in the making.",
    "I wish I had found your channel earlier.",
    "This is my go-to source for information.",
    "You're a true talent.",
    "I'm recommending your channel to everyone I know.",
    "This is the ultimate tutorial.",
    "You're making a positive impact on the world.",
    "I can't stop watching your videos.",
    "This video is a true masterpiece.",
    "You're a YouTube superstar!",
    "I've shared this with all my friends.",
    "This deserves all the praise.",
    "You're changing lives with your content.",
    "I can't believe I found your channel.",
    "This is a game-changing video.",
    "You're the best teacher on YouTube!",
    "I look forward to your future videos.",
    "This video is beyond amazing.",
    "You're a true expert in your field.",
    "I'm learning so much from you.",
    "This is the best tutorial I've ever seen.",
    "You're a YouTube sensation in the making.",
    "I can't express how much I love your work.",
    "This video is a true masterpiece.",
    "You're a legend in the YouTube community.",
    "I wish I could give this a million likes.",
    "This is the best thing on the internet.",
    "You're my YouTube hero!"
  ];
  

export function generateRandomComment() {
    const randomName = names[Math.floor(Math.random() * names.length)];
    const randomComment = comments[Math.floor(Math.random() * comments.length)];
  
    return {
      name: randomName,
      message: randomComment,
    };
  }